"""Create currency table

Revision ID: 00bdf7ca7bbe
Revises: 001
Create Date: 2026-03-27 17:11:53.781573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bdf7ca7bbe'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False, comment='ISO 4217 currency code (e.g., EUR, USD, CZK)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full currency name (e.g., Euro, US Dollar)'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Currency symbol (e.g., €, $, Kč)'),
    sa.Column('decimal_places', sa.Integer(), nullable=False, comment='Number of decimal places (0-8)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Currency is active for use'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('decimal_places >= 0 AND decimal_places <= 8', name='ck_currency_decimal_places'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
