"""Create tax_rate table

Revision ID: 0e25eb69840a
Revises: b4f2e1a9c7d3
Create Date: 2026-03-27 18:57:20.605793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e25eb69840a'
down_revision: Union[str, Sequence[str], None] = 'b4f2e1a9c7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rate',
    sa.Column('code', sa.String(length=20), nullable=False, comment='Tax rate identifier (e.g., VAT_20, VAT_21)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Descriptive name (e.g., DPH 20%)'),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Tax rate percentage (0.00 - 100.00)'),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='Start date of validity'),
    sa.Column('valid_to', sa.Date(), nullable=True, comment='End date of validity (NULL = unlimited)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the tax rate is currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate_percent >= 0 AND rate_percent <= 100', name='tax_rate_percent_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rate')
    # ### end Alembic commands ###
